### ISSUE TITLE
Rozhrani ctenare: IReaderBean

### ISSUE THREAD

**Issue by simonstastny** [ondrepe/EJA-Library#4]
Nasledujici metody v session beans rozhranni podle mne neodpovidaji. Mely by logicky vracet List<ChargeOut>, a na vstupu by mely mit Reader namisto int.
Je pro to nejaky duvod?
- ReaderDetail getChargeOutsByReader(int id);
- ReaderDetail getActiveChargeOutsByReader(int id);
- ReaderDetail getReservedChargeOutsByReader(int id);

**Comment by ondrepe** [comment]
je tam int protoze to hledas podle id uzivatele, zbytek je tedy redundantni.
vracen ReaderDetail, ktery obsaguje list vypujcek, ale i udaje o uzivateli. Je to tam kvuli tomu, ze se s tim lip pracuje pak v prezenracni vrstve, protoze si nikde nemusim pamatovat data.

**Comment by simonstastny** [comment]
OK. Jde jen o to ze to mame skrz ty rozhani nejednotny, pokud to chceme delat s idckama tak bych mel upravit zbyly rozhrani.
A pokud nechces tahat zvlast udaje o ctenari a pote udaje o jeho vypujckach s resit to takhle, tak by to asi stalo za to resit stejnym zpusobem i ostatni entity, ktery se chovaj stejne (napr.: autor by si mel drzet seznam svejch del)...

Z toho reader detail mi nebylo uplne jasny co to dela, nekam bychom tam meli popsat, ze to agreguje data z jinejch tabulek. A vzhledem k tomu ze podle toho rozhrani to vypada ze maj stejnej vstup a vystup, tak i nekam napsat ze ty data uvnitr budou ruzny (ze pro kazdou metodu bude vypadat seznam ChargeOut uvnitr ReaderDetailu jinak).

Zitra to predelam tak aby to vsude souhlasilo.

**Comment by simonstastny** [comment]
Upravil jsem ostatni rozhrani tak aby vypadala podobne tomuto.
