### ISSUE TITLE
Remote interfaces

### ISSUE THREAD

**Issue by simonstastny** [ondrepe/EJA-Library#7]
Vsechny session beans rozhrani mame Local, krom Reader a Author, ty jsou oznceny @Remote.

Kdyz jsem je psal, tak jsem tusim psal vsude Local. Potrebujeme je mit Remote?

**Comment by ondrepe** [comment]
Remote rozhrani je tam docasne a to kvuli tomu, ze mi prezentacni vrstva nechtela vracet odkaz na Local Baenu a nemel jsem chut to resit, tak jsem tam docasne dal Remote

**Comment by simonstastny** [comment]
Ok, on to nijak nestrhaval, jen to nedoporucoval, protoze s tim vetsinou studenti mivaji problemy, ktery u Local nebyvaj.. Asi neni potreba zatim nijak resit...
