### ISSUE TITLE
Odevzdání CHECKPOINT 2

### ISSUE THREAD

**Issue by simonstastny** [ondrepe/EJA-Library#8]
Odevzdání a prezentace proběhla, ale ještě je nutno upravené zdrojáky nahrát do upload systému.

**Comment by ondrepe** [comment]
sorry jsem usnul v sede, pri cekani na stahnuti knihoven mavenem.

**Comment by simonstastny** [comment]
priznam se, ze jsem to trochu cekal, tak jsem byl pripravenej :)
ale je potreba se tam stavit v tu stredu, probrat s nim zbytek a nechat si za to dat body..

**Comment by simonstastny** [comment]
Vycistil jsem a nahral do upload systemu.

NICMENE VE STREDU MUSIME OBA NA PREDNASKU A NECHAT SI DAT BODY.
